"""add variant column for A/B analysis

Revision ID: 990c1570c7e2
Revises: 97a8db9e65fa
Create Date: 2026-09-14 17:53:13.022591+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "990c1570c7e2"
down_revision: str | None = "97a8db9e65fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inference_logs", sa.Column("variant", sa.String(length=64), nullable=True))
    op.create_index(
        "ix_inference_logs_variant",
        "inference_logs",
        ["variant", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("variant IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_inference_logs_variant",
        table_name="inference_logs",
        postgresql_where=sa.text("variant IS NOT NULL"),
    )
    op.drop_column("inference_logs", "variant")
    # ### end Alembic commands ###
