"""create inference_logs table

Revision ID: 97a8db9e65fa
Revises:
Create Date: 2026-09-14 16:58:38.030837+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97a8db9e65fa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_tier", sa.String(length=32), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("image_sha256", sa.String(length=64), nullable=True),
        sa.Column("image_bytes", sa.Integer(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("image_format", sa.String(length=16), nullable=True),
        sa.Column("top_label", sa.String(length=256), nullable=True),
        sa.Column("top_class_id", sa.Integer(), nullable=True),
        sa.Column("top_probability", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inference_logs_created_at",
        "inference_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_inference_logs_errors",
        "inference_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status != 'success'"),
    )
    op.create_index(
        "ix_inference_logs_image_sha256", "inference_logs", ["image_sha256"], unique=False
    )
    op.create_index(
        "ix_inference_logs_model_created",
        "inference_logs",
        ["model_name", "model_version", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_inference_logs_user_created",
        "inference_logs",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inference_logs_user_created", table_name="inference_logs")
    op.drop_index("ix_inference_logs_model_created", table_name="inference_logs")
    op.drop_index("ix_inference_logs_image_sha256", table_name="inference_logs")
    op.drop_index(
        "ix_inference_logs_errors",
        table_name="inference_logs",
        postgresql_where=sa.text("status != 'success'"),
    )
    op.drop_index("ix_inference_logs_created_at", table_name="inference_logs")
    op.drop_table("inference_logs")
    # ### end Alembic commands ###
