#!/usr/bin/env python3
"""Regenerate the benchmark figures quoted in prose from the measured data.

Every document that quotes a latency number is a copy of `benchmarks/results.json`
that decays the moment the sweep is re-run. That is not hypothetical: a single
regeneration left five documents quoting TensorRT at 3.49 ms while the committed
data said 3.63 ms, and a later one moved it again to 3.51 ms. Run-to-run
variance on a shared machine is a few percent, so hand-copied numbers are wrong
almost immediately and nothing notices.

So the headline table is generated, not written. Each document marks the region
it delegates::

    <!-- BEGIN:headline-latency -->
    ...generated, do not edit...
    <!-- END:headline-latency -->

Usage::

    uv run python scripts/sync_docs.py            # rewrite the blocks
    uv run python scripts/sync_docs.py --check    # fail if any is stale (CI)

Numbers outside these blocks are still hand-written and still need judgement;
this closes the one category that is purely mechanical.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

BEGIN = "<!-- BEGIN:headline-latency -->"
END = "<!-- END:headline-latency -->"

#: Documents carrying the block. Each is rewritten in place.
TARGETS = (
    Path("README.md"),
    Path("docs/README.md"),
    Path("docs/technical-writeup.md"),
    Path("benchmarks/ANALYSIS.md"),
)

#: Rows to render, in order, as (backend, precision, label).
ROWS = (
    ("pytorch-cuda", "fp32", "PyTorch eager FP32"),
    ("pytorch-cuda", "bf16", "PyTorch eager bf16"),
    ("onnxruntime-tensorrt", "fp16", "**TensorRT FP16**"),
    ("onnxruntime-cuda", "fp32", "ONNX Runtime CUDA FP32"),
    ("onnxruntime-cpu", "int8", "ONNX Runtime CPU INT8"),
)

BATCH_SIZE = 32


def render(results: list[dict[str, Any]]) -> str:
    """Render the classifier's batch-32 comparison, relative to eager FP32."""
    indexed = {
        (row["backend"], row["precision"]): row
        for row in results
        if row["model"] == "classifier" and row["batch_size"] == BATCH_SIZE
    }

    baseline = indexed.get(("pytorch-cuda", "fp32"))
    if baseline is None:
        raise SystemExit(
            "benchmarks/results.json has no pytorch-cuda fp32 row at batch "
            f"{BATCH_SIZE}; the speedup column has no baseline to divide by."
        )

    lines = [
        "| Backend | Latency | Throughput | Speedup |",
        "| --- | ---: | ---: | ---: |",
    ]
    for backend, precision, label in ROWS:
        row = indexed.get((backend, precision))
        if row is None:
            continue
        speedup = baseline["mean_ms"] / row["mean_ms"]
        latency = f"{row['mean_ms']:.2f} ms"
        throughput = f"{row['throughput_ips']:,.0f} img/s"
        if label.startswith("**"):
            latency, throughput = f"**{latency}**", f"**{throughput}**"
            speedup_cell = f"**{speedup:.2f}x**"
        else:
            speedup_cell = f"{speedup:.2f}x"
        lines.append(f"| {label} | {latency} | {throughput} | {speedup_cell} |")

    return "\n".join(lines)


def apply_block(text: str, block: str, path: Path) -> str:
    """Replace the delegated region, leaving everything else untouched."""
    start = text.find(BEGIN)
    stop = text.find(END)
    if start == -1 or stop == -1:
        raise SystemExit(f"{path} has no {BEGIN} / {END} block")
    if stop < start:
        raise SystemExit(f"{path} has {END} before {BEGIN}")

    head = text[: start + len(BEGIN)]
    tail = text[stop:]
    notice = "<!-- Generated by scripts/sync_docs.py; edits here are overwritten. -->"
    return f"{head}\n{notice}\n\n{block}\n\n{tail}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=Path("benchmarks/results.json"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any document is out of date, without writing",
    )
    args = parser.parse_args(argv)

    if not args.results.exists():
        raise SystemExit(
            f"{args.results} not found. Generate it with:\n"
            f"  uv run python -m models.optimisation.run_benchmarks --models all"
        )

    block = render(json.loads(args.results.read_text())["results"])

    stale: list[Path] = []
    for path in TARGETS:
        current = path.read_text()
        updated = apply_block(current, block, path)
        if current == updated:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(updated)

    if args.check and stale:
        print("Out of date with benchmarks/results.json:")
        for path in stale:
            print(f"  {path}")
        print("\nRegenerate with:  uv run python scripts/sync_docs.py")
        return 1

    if stale:
        print("Updated:")
        for path in stale:
            print(f"  {path}")
    else:
        print("All documents are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
